### ISSUE TITLE
Kanban Board setup for the final capstone

### ISSUE THREAD

**Issue by Tadesse-Alemayehu** [marurevi/YellowRooms-Front#14]
[Link to the Kanban board](https://github.com/users/marurevi/projects/3/views/1)
- We are four (4) in this team. 

> @Tadesse-Alemayehu 
> @anagudelogu 
> @marurevi 
> @AxelSoler 

### Our Kanban board

https://user-images.githubusercontent.com/69077061/190270018-09626f76-dfc5-4f74-85c1-211cd9b4b8b2.mp4

**Comment by mcrd25** [comment]
Hi Team (@Tadesse-Alemayehu @anagudelogu @marurevi @AxelSoler), 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
